#!/bin/bash
DIR="TeamSpeak3-Client-linux_amd64"
INSTALLER="TeamSpeak3-Client-linux_amd64-3.0.10.run"

cd /opt/
bash /tmp/$INSTALLER
mv /tmp/teamspeak3-client.desktop /opt/$DIR/teamspeak3-client.desktop

# Add icons to the system icons
XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null`"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi
for icon in "/opt/$DIR/pluginsdk/docs/client_htmli/images/"logo.png; do
  size="${icon##*/product_logo_}"
  "$XDG_ICON_RESOURCE" install --size "${size%.png}" "$icon" "teamspeak3-client"
done

# Add an entry to the system menu
XDG_DESKTOP_MENU="`which xdg-desktop-menu 2> /dev/null`"
UPDATE_MENUS="`which update-menus 2> /dev/null`"
if [ ! -x "$XDG_DESKTOP_MENU" ]; then
  echo "Error: Could not find xdg-desktop-menu" >&2
  exit 1
fi
"$XDG_DESKTOP_MENU" install /opt/$DIR/teamspeak3-client.desktop

if [ -x "$UPDATE_MENUS" ]; then
  update-menus
fi

# Add link in /usr/bin 
ln -s /opt/$DIR/ts3client_runscript.sh /usr/bin/teamspeak3-client
chmod -R o+w /opt/$DIR
rm -f /tmp/$INSTALLER
