#!/bin/bash

# Add icons to the system icons
XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null`"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi
for icon in "/opt/teamspeak3-client/pluginsdk/docs/client_htmli/images/"logo.png; do
  size="${icon##*/product_logo_}"
  "$XDG_ICON_RESOURCE" install --size "${size%.png}" "$icon" "teamspeak3-client"
done

# Add an entry to the system menu
XDG_DESKTOP_MENU="`which xdg-desktop-menu 2> /dev/null`"
UPDATE_MENUS="`which update-menus 2> /dev/null`"
if [ ! -x "$XDG_DESKTOP_MENU" ]; then
  echo "Error: Could not find xdg-desktop-menu" >&2
  exit 1
fi
"$XDG_DESKTOP_MENU" install /opt/teamspeak3-client/teamspeak3-client.desktop

if [ -x "$UPDATE_MENUS" ]; then
  update-menus
fi

# Add link in /usr/bin 
ln -s /opt/teamspeak3-client/ts3client_runscript.sh /usr/bin/teamspeak3-client
